spring.application.name=ratings-data-service
server.port=8083
spring.datasource.url=jdbc:mysql://localhost:3306/ratings_db
spring.datasource.username=root
spring.datasource.password=619619619
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.sql.init.mode=always